[feature] Add bootup_delay option #108
openwisp/openwrt-openwisp-monitoring pull request #111
Opened 2022-12-09 11:14 UTC by pandafy

Closes #108

2022-12-09 16:56 UTC, pandafy commented on openwisp-monitoring/files/monitoring.agent
> +		fi
While testing these changes locally I found that this part of code is executed twice 

```text
root@02-tplink-archer:~# rm -rf /tmp/openwisp/monitoring/;  /etc/init.d/openwisp-monitoring restart; logread -f
openwisp-monitoring: OpenWISP monitoring daemon stopping
openwisp-monitoring: OpenWISP monitoring daemon started
Fri Dec  9 16:50:26 2022 daemon.info openwisp: Delaying startup for 5 seconds...
Fri Dec  9 16:50:32 2022 daemon.info openwisp: Delaying startup for 4 seconds...
```

Upon deeper investigation, I found that the script exists unexpectedly while executing the `sleep` statement (i.e. the statements after sleep are not executed). When the script executes for the second time, the statements following `sleep` are executed. When I comment out the `sleep` statement the script runs without any issues (no duplicate delays). 

I wonder if there is something that kills the script when it executes the `sleep` statement. I didn't find anything fruitful while running the openwisp-monitoring package in verbose mode. I also tried restarting the openwisp-monitoring agent with `PROCD_DEBUG=1` as mentioned in https://openwrt.org/docs/guide-developer/procd-init-scripts#debugging

2022-12-09 17:40 UTC, pandafy commented on openwisp-monitoring/files/monitoring.agent
> +		fi
Thanks to @nemesisdesign, I finally found the reason why the script was getting reloaded. It was due to the `collect_data` function sending `SIGUSR1` signal. 

https://github.com/openwisp/openwrt-openwisp-monitoring/blob/6d9340d62cc502d1a1e85fdbb77460c836004d98/openwisp-monitoring/files/monitoring.agent#L109-L112

2022-12-19 22:52 UTC, nemesisdesign requested changes

2022-12-19 22:52 UTC, nemesisdesign commented on openwisp-monitoring/files/monitoring.agent
> +				logger "Delaying sending metrics for $DELAY seconds..." \
Delaying sending metrics?
I would make the message more generic, eg: "Delaying initialization of the monitoring agent for $DELAY seconds."

2022-12-19 22:52 UTC, nemesisdesign commented on openwisp-monitoring/files/monitoring.agent
> +		if [ ! -f "$BOOTUP" ]; then
I think moving this block of code in its own function and calling only the function here (eg `bootup_delay`) would improve readability and maintain consistency with the rest of the code in this file.

2022-12-20 14:25 UTC, nemesisdesign approved these changes

2022-12-20 18:35 UTC, merged