[tests] Changed JSON string assertions to data structure assertions #109
openwisp/openwrt-openwisp-monitoring pull request #115
Opened 2023-01-02 12:22 UTC by Aryamanz29

Closes #109

2023-01-11 22:44 UTC, nemesisdesign requested changes

2023-01-11 22:44 UTC, nemesisdesign commented on openwisp-monitoring/tests/test_neighbors.lua
> +  luaunit.assertEquals(netjson['neighbors'][3]["mac"], "bc:0f:9a:17:5a:5c")
same here

2023-01-11 22:44 UTC, nemesisdesign commented on openwisp-monitoring/tests/test_wifi.lua
> +  luaunit.assertEquals(netjson["interfaces"][5]["wireless"]["tx_power"], 20)
same here

2023-01-11 22:44 UTC, nemesisdesign commented on openwisp-monitoring/tests/test_wifi.lua
> +  luaunit.assertEquals(netjson["interfaces"][5]["statistics"]["tx_packets"], 2367747)
same here

2023-01-12 08:42 UTC, Aryamanz29 commented on openwisp-monitoring/tests/test_dhcp.lua
> +  luaunit.assertEquals(netjson["dhcp_leases"][1]["client_id"], "01:e8:6a:64:3e:4a:3c")
You're right, we should avoid changing the assertion order of existing `unittests`. I have configured some `lua-formatter` extensions in my code editor, and I believe it restructured the code based on the lua table index. I have reversed this change in [`c97b3f2` (#115)](https://github.com/openwisp/openwrt-openwisp-monitoring/pull/115/commits/c97b3f2f2932e3593efea685c1a256005891ee9a)

2023-01-12 16:18 UTC, nemesisdesign approved these changes

2023-01-12 16:18 UTC, merged