[enhancement] Add curl cacert capath options #134
openwisp/openwrt-openwisp-monitoring pull request #135
Opened 2024-07-03 07:20 UTC by SLSC1907

Addresses #134

Update monitoring.init and monitoring.agent for curl cacert capath options from openwisp-config configuration.

2024-07-03 13:29 UTC, nemesifier requested changes
Looks good @SLSC1907, please add these options to the [Configuration Options section in the README](https://github.com/openwisp/openwrt-openwisp-monitoring?tab=readme-ov-file#configuration-options).

2024-07-04 02:06 UTC, SLSC1907 commented
Thanks for the feedback.
I didn't include it as the documentation and configuration is set from the openwrt-openwisp-config package.

i.e. These UCI options aren't read from `/etc/config/openwisp-monitoring` but are pulling the options from /etc/config/openwisp just like the existing verify_ssl option.

As it exists, if you use the cacert and capath options with verify_ssl in openwisp-config, the monitoring package will fail to upload / verify the certificate.

The options are documented however in the monitoring.agent printed help output, like the verify_ssl option.

Would you like all the Openwisp general config items documented in the readme for openwisp-monitoring?

My plan is to add a note underneath regarding the application also pulls configuration options from /etc/config/openwisp. I can write a separate documentation update too? Not sure how you'd like to proceed.

2024-07-04 23:23 UTC, nemesifier approved these changes

2024-07-04 23:24 UTC, nemesifier approved these changes
@SLSC1907 you're right, documenting these options is not needed, I had missed this detail in my previous review, thanks for pointing it out. I fixed some issues with whitespace (we use tabs here instead of spaces), not it can be merged. Thanks for contributing! :pray:

2024-07-04 23:25 UTC, merged