[fix] Fix errors in package and improve debugging
openwisp/openwrt-openwisp-monitoring pull request #42
Opened 2021-07-13 21:00 UTC by devkapilbansal

2021-07-13 21:02 UTC, devkapilbansal commented on openwrt-openwisp-monitoring/files/monitoring.init
> +    procd_set_param stderr 1
Adding this to log all errors in the instance so that it can be accessed using logread

2021-07-13 21:02 UTC, devkapilbansal commented on openwrt-openwisp-monitoring/files/monitoring.init
> +    procd_set_param command $PROG $base_url $uuid $key $verify_ssl $interval $monitored_interfaces
Reverting quotes as this was causing `monitoring.agent` to read `--url http://www.....` as one word

2021-07-17 18:53 UTC, nemesisdesign requested changes
With this patch, the daemon sends data to OpenWISP Monitoring :+1: .

Here's the issues I found during testing.

### Non verbose mode

I see these two lines in non-verbose mode:

```
Fri Jul 16 10:32:36 2021 daemon.info monitoring: Collecting NetJSON Monitoring data
Fri Jul 16 10:32:38 2021 daemon.info monitoring: Data sent successfully.
```

But this output should not be shown in non-verbose mode, otherwise logs will be filled with irrelevant lines.

### Traffic stats seem missing

I don't see traffic stats being collected on the device I am using for testing, once I installed this branch and remove the old monitoring scripts, the traffic charts are flat zero.

Did you test this?

### Verbose mode testing

Here's a few problems I see with verbose mode.

#### Identifeir different

The logread output uses different identifiers: monitoring, openwisp_monitoring, openwisp_monitoring[<number>]. This is bad because log collectors will interpret these as different programs, can you make sure this is always the same? `monitoring` seems to generic, I think it should be `openwisp_monitoring`.

#### Logged response can be improved

Here's an example output: `Data not sent successfully. Response code is {"detail":"Authentication credentials were not provided."}403.`. The message is readable but it's weird. The response body is `{"detail":"Authentication credentials were not provided."}` while the response status code is 403. Can you turn this into something like:
`The response received was: 403 {"detail":"Authentication credentials were not provided."}`?

#### Run with verbose mode redundant

This is showing up with verbose mode:

```
Fri Jul 16 10:53:31 2021 daemon.err monitoring: Run with verbose mode to find more.
Fri Jul 16 10:53:31 2021 daemon.err openwisp_monitoring[4023]: monitoring: Run with verbose mode to find more.
``` 

1. we're already in verbose mode so we don't need to send this output.
2. if we're not in verbose mode, ensure the output is not repeated twice
3. do you see how one log line is identified by `daemon.err monitoring` and the otehr one by `daemon.err openwisp_monitoring[4023]`? This was mentioned in one of the previous review sections but please make sure to avoid it.

2021-07-17 18:53 UTC, nemesisdesign commented on openwrt-openwisp-monitoring/files/monitoring.config
> +	option monitored_interfaces '"*"'
requiring the user to remember to wrap the value around double quotes is really bad and weird. I think we can do better than this.

2021-07-17 18:53 UTC, nemesisdesign commented on openwrt-openwisp-monitoring/files/monitoring.init
>      monitored_interfaces="--monitored_interfaces $monitored_interfaces"
does 

```
monitored_interfaces="--monitored_interfaces \"$monitored_interfaces\""
```

allow us to not having to wrap the value in quotes in the UCI config file?

2021-07-22 10:11 UTC, devkapilbansal commented
Thanks for testing this. I made some changes as follows:

**Non Verbose Mode**
Unnecessary lines have been removed. Those two lines will be logged in verbose mode only. 

**Traffic stats**
I just ensured that traffic stats are sent in netjson response from the scripts. Will test it to be more sure.

**Identifier**
All messages tagged with `monitoring` are changed to `openwisp_monitoring`. But in verbose_mode, messages are coming as `openwisp_monitoring[number]` and I am unsure of that number. I think that this is the id of procd instance. :thinking: 

**Redundant Log Messages**
Messages were logged twice in verbose mode. This was because messages were logged once by the logger tagged with the identifier we were passing.These messages were catched by the procd instance and logged again with procd instance name as the identifier.
For this, I removed the identifier from the messages I was logging in verbose mode so that we get relevant lines only when grepping log messages.
If we use `logread` then the messages are redundant in verbose_mode but passing `logread | grep openwisp_monitoring` will show the message once.

2021-07-24 23:37 UTC, nemesisdesign approved these changes
I did a couple of minor improvements https://github.com/openwisp/openwrt-openwisp-monitoring/pull/42/commits/021307c57289763847e3f3f59dda051ab1751d9e https://github.com/openwisp/openwrt-openwisp-monitoring/pull/42/commits/0083e00d3824833aea1de0062e84f2be97acf7e3.

Tested and it's working better, I think there's room for improvements but let's merge and I will open new issues for improvements.

2021-07-24 23:38 UTC, merged