[fix] Modified functions using popen to use temporary files #15 #32
openwisp/openwrt-openwisp-monitoring pull request #48
Opened 2021-08-09 19:12 UTC by devkapilbansal

Fixes #15
Fixes #32

2021-08-09 23:57 UTC, nemesisdesign reviewed
I did a search in the files of the project and I see two occurrences of `io.popen()` that are not being changed, can you please double check?

See also my comment below.

2021-08-09 23:57 UTC, nemesisdesign commented on openwrt-openwisp-monitoring/files/lib/openwisp/monitoring_utils.lua
> +  return output_file
shouldn't the file be removed once the output is read? And are you sure using tmp files is really necessary?

Wouldn't it be enough to just do:

```lua
output = commmand_file:read("*a")
command_file:close()
return output
```

We weren't doing this before explicitly for every call.

2021-08-09 23:58 UTC, nemesisdesign reviewed
I did a search in the files of the project and I see two occurrences of `io.popen()` that are not being changed, can you please double check?

See also my comment below.

2021-08-10 18:37 UTC, devkapilbansal commented
> I did a search in the files of the project and I see two occurrences of `io.popen()` that are not being changed, can you please double check?
> 
> See also my comment below.

I did it intentionally. The reason being:
- The `utils.popen` was getting cached in some cases which results in breaking the tests. The solution can be to mock define utils.popen too in each file which I don't think is a cleaner solution.
- We need to modify popen only when we are performing operations before closing the file. The only scenario in our case was looping over the output using `:lines()` function.

2021-08-10 18:38 UTC, devkapilbansal commented
Hi @nemesisdesign , I updated the code to use split instead as we agreed in the chat.

2021-08-12 02:14 UTC, nemesisdesign reviewed
there's a lot of repetition in this PR, why not create a utility function which does the read, close and returning of the output?

This also ensures that whoever will put their hands on this code will keep reusing our function and avoid messing it up again by forgetting to close a pipe.

2021-08-13 00:58 UTC, nemesisdesign commented
> > there's a lot of repetition in this PR, why not create a utility function which does the read, close and returning of the output?
> > This also ensures that whoever will put their hands on this code will keep reusing our function and avoid messing it up again by forgetting to close a pipe.
> 
> I too tried doing something similar. But if I do it in utils function and import it in other sub-modules, then it may not be possible for now to keep them separated from one another. The cache property of `require` is breaking the functionalities in tests

I hope we can find a way to do it, it would be better, I created an issue here: https://github.com/openwisp/openwrt-openwisp-monitoring/issues/61.

2021-08-13 01:16 UTC, nemesisdesign requested changes

2021-08-13 01:16 UTC, nemesisdesign commented on openwrt-openwisp-monitoring/files/lib/openwisp/interfaces.lua
> +
duplicating the same function in each file is actually worse Kapil. If duplicating two lines of code is not good, how can duplicating 6 lines of code be better? Please rollback how it was before.

2021-08-15 21:42 UTC, nemesisdesign approved these changes
Thanks

2021-08-15 21:42 UTC, merged