Issues/95 fix ula prefix
openwisp/openwrt-openwisp-monitoring pull request #96
Opened 2022-05-19 23:35 UTC by devkapilbansal

2022-05-25 22:35 UTC, nemesisdesign requested changes
Looking good! I see a couple of things that should be improved and a flaw (the test is not added to the runtests script!). See below for more info.

2022-05-25 22:35 UTC, nemesisdesign commented on openwisp-monitoring/tests/test_ula.lua
> +package.path = package.path .. ";../files/lib/openwisp-monitoring/?.lua" ..
please rename it to `test_ula_prefix.lua` and make sure it's added to the `runtests` script otherwise it will not be run during tests.

2022-05-25 22:35 UTC, nemesisdesign commented on openwisp-monitoring/files/lib/openwisp-monitoring/interfaces.lua
> +                                 ''
Is the formatter doing this? It looks really ugly, doesn't it.
Can we find a way to avoid this weirdness and keep it on the line above?

2022-05-26 21:03 UTC, devkapilbansal commented on openwisp-monitoring/luaformat.config
> +column_limit: 88
I have to change `column_limit` of the formatter and that introduces changes in other files

2022-05-27 13:17 UTC, nemesisdesign requested changes
isn't it possible to just disable the formatter for this particular line?
https://github.com/Koihik/LuaFormatter#disable-formatting-for-a-line-or-block

We cannot change the global configuration every time there's a line which looks off, we need the two packages (this one and openwisp-config) to have consistent configuration and moreover we don't want to pollute the history with unnecessary changes.

2022-06-01 23:31 UTC, nemesisdesign approved these changes
Thanks!

2022-06-01 23:32 UTC, merged